addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.13")
addSbtPlugin("com.github.gseitz"         % "sbt-release"  % "1.0.13")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly" % "0.15.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"   % "5.6.0")
