addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.13")
addSbtPlugin("com.github.gseitz"         % "sbt-release"  % "1.0.13")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"   % "5.6.0")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype" % "3.9.4")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"      % "2.0.1")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"  % "0.5.3")
